-- Generated by WatermarkRoundTripTest.php using FMP's OracleSqlManagerService.
-- Paste this entire SELECT into the KN Oracle console.
-- Expected: FMP_ACTUAL_BOUND = 0; CORRECT_BOUND = 1.
-- No KN table scan: both branches use the same single synthetic DUAL row.
SELECT 'FMP_ACTUAL_BOUND' AS mode, q."count" AS included_rows
FROM (
  SELECT COUNT(*) AS "count" FROM (
    SELECT * FROM (
      SELECT FROM_TZ(TIMESTAMP '2026-08-05 13:00:00', 'Europe/Ljubljana') AS DATUM_SYS FROM dual
    ) x WHERE 1 = 1
      AND DATUM_SYS >= TO_TIMESTAMP_TZ('2026-08-05 12:26:56.000000+00:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
      AND DATUM_SYS <= TO_TIMESTAMP_TZ('2026-08-08 02:50:00.000000+00:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
  ) x
) q
UNION ALL
SELECT 'CORRECT_BOUND' AS mode, q."count" AS included_rows
FROM (
  SELECT COUNT(*) AS "count" FROM (
    SELECT * FROM (
      SELECT FROM_TZ(TIMESTAMP '2026-08-05 13:00:00', 'Europe/Ljubljana') AS DATUM_SYS FROM dual
    ) x WHERE 1 = 1
      AND DATUM_SYS >= TO_TIMESTAMP_TZ('2026-08-05 12:26:56.000000+02:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
      AND DATUM_SYS <= TO_TIMESTAMP_TZ('2026-08-08 02:50:00.000000+00:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
  ) x
) q;

-- Show the interpretation of your October 6 watermark explicitly.
SELECT
  TO_CHAR(TO_TIMESTAMP_TZ('2026-10-06 15:01:29.000000+00:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
    AT TIME ZONE 'Europe/Ljubljana', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') AS fmp_cutoff_ljubljana,
  TO_CHAR(TO_TIMESTAMP_TZ('2026-10-06 15:01:29.000000+02:00', 'YYYY-MM-DD HH24:MI:SS.FF6TZH:TZM')
    AT TIME ZONE 'Europe/Ljubljana', 'YYYY-MM-DD HH24:MI:SS TZH:TZM') AS correct_cutoff_ljubljana
FROM dual;
-- Expected: 17:01:29 +02:00 versus 15:01:29 +02:00.
