SELECT
    j."ID" AS dst_pripis_podatki_pk,
    j."DST_SID" AS dst_sid,
    j."EID" AS eid,
    j."ID_MODEL" AS id_model,
    j."ERROR_MSG" AS error_msg,
    j."RAVEN" AS raven,
    j."CONA_IME" AS cona_ime,
    j."D_DST" AS d_dst,
    j."IZMERA" AS izmera,
    j."LETO_IZG_STA" AS leto_izg_sta,
    j."VT_DST" AS vt_dst,
    j."POV_LETO_OBN" AS pov_leto_obn,
    j."F_OBN" AS f_obn,
    j."T_LAST" AS t_last,
    j."F_LAST" AS f_last,
    j."F_NK" AS f_nk,
    j."POVR_ZPS" AS povr_zps,
    j."F_D_DST" AS f_d_dst,
    j."VT_ZPS_M2" AS vt_zps_m2,
    j."VT_PRI" AS vt_pri,
    j."VPLIVI" AS vplivi,
    j."F_ODD" AS f_odd,
    j."T_DP" AS t_dp,
    j."F_DP" AS f_dp,
    j."T_LEGE" AS t_lege,
    j."F_LEGE" AS f_lege,
    j."F_GAR" AS f_gar,
    j."POVR_PPP_P" AS povr_ppp_p,
    j."POVR_PPL_P" AS povr_ppl_p,
    j."FAKTOR_P" AS faktor_p,
    j."F_LP" AS f_lp,
    j."POVR_DP_P" AS povr_dp_p,
    j."VT_DP_M2_P" AS vt_dp_m2_p,
    j."POVR_PPL_L" AS povr_ppl_l,
    j."POVR_PPP_L" AS povr_ppp_l,
    j."FAKTOR_L" AS faktor_l,
    j."F_PL" AS f_pl,
    j."POVR_DP_L" AS povr_dp_l,
    j."VT_DP_M2_L" AS vt_dp_m2_l,
    j."POVR_DP_TUR" AS povr_dp_tur,
    j."VT_DP_M2_TUR" AS vt_dp_m2_tur,
    j."JN_REV_NUM" AS jn_rev_num,
    j."VREDNOST" AS vrednost,
    TO_CHAR(FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana'),
            'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_from,
    CAST(NULL AS VARCHAR2(40)) AS valid_to,
    CAST(rf.CREATED AS TIMESTAMP) AS date_change
FROM EV.DST_PRIPIS_PODATKI j
JOIN EV.REVISION rf ON j."JN_REV_NUM" = rf.REV_NUM;
