SELECT TO_CHAR(j.DST_SID) || '-' || TO_CHAR(j.JN_REV_NUM) AS jn_del_stavbe_pk,
       j.DST_SID, j.STA_SID, j.STEV_DST, j.STEV_STAN, j.POVRSINA, j.UPOR_POV, j.HS_MID,
       j.LETO_OBN_OKEN, j.LETO_OBN_INST, j.ST_NADSTROPJA, j.ID_LEGA, j.PROSTORNINA,
       j.IMA_DVIGALO_DN, j.VISINA_ETAZE, j.ID_DR_DST, j.JN_REV_NUM, j.JN_REV_NUM_TO,
       j.JN_REV_NUM_PREV, j.DELEZ_DST_STAVBA, j.ZPS_DST, j.ID_MODEL, j.CCSI_STAR,
       j.IMA_KATAS_VPIS_DN, j.EID, j.HS_MID_CENX, j.HS_MID_CENY,
       CAST(TRIM(j.JN_STATUS) AS VARCHAR2(1)) AS jn_status,
       TO_CHAR(FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana'), 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_from,
       TO_CHAR(FROM_TZ(CAST(rt.CREATED AS TIMESTAMP), 'Europe/Ljubljana'), 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_to,
       CAST(COALESCE(rt.CREATED, rf.CREATED) AS TIMESTAMP) AS date_change
FROM EV.JN_DEL_STAVBE j JOIN EV.REVISION rf ON j.JN_REV_NUM = rf.REV_NUM
LEFT JOIN EV.REVISION rt ON j.JN_REV_NUM_TO = rt.REV_NUM
WHERE j.JN_STATUS <> 'X'
