SELECT
    j."ID" AS parc_pripis_podatki_pk,
    j."ID" AS kn_page_id,
    j."PC_MID" AS pc_mid,
    j."EID" AS eid,
    j."ID_MODEL" AS id_model,
    j."ERROR_MSG" AS error_msg,
    j."RAVEN" AS raven,
    j."CONA_IME" AS cona_ime,
    j."IZMERA" AS izmera,
    j."POVR_HME" AS povr_hme,
    j."VT_HME_M2" AS vt_hme_m2,
    j."POVR_VIN" AS povr_vin,
    j."VT_VIN_M2" AS vt_vin_m2,
    j."POVR_SAD" AS povr_sad,
    j."VT_SAD_M2" AS vt_sad_m2,
    j."POVR_OLJ" AS povr_olj,
    j."VT_OLJ_M2" AS vt_olj_m2,
    j."VT_Z_M2" AS vt_z_m2,
    j."BONITETA" AS boniteta,
    j."F_BON" AS f_bon,
    j."RK" AS rk,
    j."F_RK" AS f_rk,
    j."ODPRTOST" AS odprtost,
    j."F_ODP" AS f_odp,
    j."F_POVR" AS f_povr,
    j."POVR_A" AS povr_a,
    j."VT_A_M2" AS vt_a_m2,
    j."POVR_B" AS povr_b,
    j."VT_B_M2" AS vt_b_m2,
    j."POVR_C" AS povr_c,
    j."VT_C_M2" AS vt_c_m2,
    j."POVR_D" AS povr_d,
    j."VT_D_M2" AS vt_d_m2,
    j."POVR_E" AS povr_e,
    j."VT_E_M2" AS vt_e_m2,
    j."POVR_F" AS povr_f,
    j."VT_F_M2" AS vt_f_m2,
    j."POVR_G" AS povr_g,
    j."VT_G_M2" AS vt_g_m2,
    j."POVR_H" AS povr_h,
    j."VT_H_M2" AS vt_h_m2,
    j."POVR_VOD" AS povr_vod,
    j."VT_VOD_M2" AS vt_vod_m2,
    j."POVR_POZ" AS povr_poz,
    j."VT_POZ_M2" AS vt_poz_m2,
    j."JN_REV_NUM" AS jn_rev_num,
    j."F_ODD" AS f_odd,
    j."VPLIVI" AS vplivi,
    j."VREDNOST" AS vrednost,
    TO_CHAR(FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana'),
            'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_from,
    CAST(NULL AS VARCHAR2(40)) AS valid_to,
    TO_CHAR(FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana'),
            'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS date_change,
    CAST(rf.CREATED AS TIMESTAMP) AS kn_delta_date_change
FROM EV.PARC_PRIPIS_PODATKI j
JOIN EV.REVISION rf ON j."JN_REV_NUM" = rf.REV_NUM;
