SELECT TO_CHAR(j.ID_PE) || '-' || TO_CHAR(j.JN_REV_NUM) AS jn_posebna_enota_pk,
       j.ID_PE, j.ID_PN, j.NAZIV, j.ID_MODEL, j.VREDNOST, j.JN_REV_NUM,
       j.JN_REV_NUM_TO, j.JN_REV_NUM_PREV, j.RAVEN, j.CENX, j.CENY, j.NASLOV,
       j.POSPLOSENA_VREDNOST, j.PODATKI, j.OB_MID, j.NASLOV_VROCANJA, j.TIP,
       j.FAKTOR_PO, j.ID_DOKUMENT, j.DELITEV_STATUS, j.DELITEV_MSG, j.DAT_PLOMBA,
       j.PLOMBA_RAZLOG, j.ID_MODEL_VER,
       CAST(TRIM(j.JN_STATUS) AS VARCHAR2(1)) AS jn_status,
       TO_CHAR(FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana'), 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_from,
       TO_CHAR(FROM_TZ(CAST(rt.CREATED AS TIMESTAMP), 'Europe/Ljubljana'), 'YYYY-MM-DD"T"HH24:MI:SS.FF TZH:TZM') AS valid_to,
       CAST(COALESCE(rt.CREATED, rf.CREATED) AS TIMESTAMP) AS date_change
FROM EV.JN_POSEBNA_ENOTA j JOIN EV.REVISION rf ON j.JN_REV_NUM = rf.REV_NUM
LEFT JOIN EV.REVISION rt ON j.JN_REV_NUM_TO = rt.REV_NUM
WHERE j.JN_STATUS <> 'X'
