SELECT TO_CHAR(j.STA_SID) || '-' || TO_CHAR(j.JN_REV_NUM) AS jn_sta_pk,
       j.STA_SID, j.KO_SIFKO, j.STEV_ST, j.ST_ETAZ, j.LETO_IZG_STA,
       j.LETO_OBN_STREHE, j.LETO_OBN_FASADE, j.ID_KONSTRUKCIJA,
       j.IMA_VODOVOD_DN, j.IMA_ELEKTRIKO_DN, j.IMA_KANALIZACIJO_DN,
       j.IMA_PLIN_DN, j.ID_TIP_STAVBE, j.CENX, j.CENY, j.ST_STANOVANJ,
       j.ST_POSLOVNIH_PROSTOROV, j.JN_REV_NUM, j.JN_REV_NUM_TO,
       j.JN_REV_NUM_PREV, j.POV_STAVBE, j.ZPS_STAVBA, j.OB_MID, j.EID,
       CAST(TRIM(j.JN_STATUS) AS VARCHAR2(1)) AS jn_status,
       FROM_TZ(CAST(rf.CREATED AS TIMESTAMP), 'Europe/Ljubljana') AS valid_from,
       FROM_TZ(CAST(rt.CREATED AS TIMESTAMP), 'Europe/Ljubljana') AS valid_to,
       FROM_TZ(CAST(COALESCE(rt.CREATED, rf.CREATED) AS TIMESTAMP), 'Europe/Ljubljana') AS date_change
FROM EV.JN_STAVBA j JOIN EV.REVISION rf ON j.JN_REV_NUM = rf.REV_NUM
LEFT JOIN EV.REVISION rt ON j.JN_REV_NUM_TO = rt.REV_NUM
WHERE j.JN_STATUS <> 'X'
